---
# This file contains configuration for the LGTM tool: https://lgtm.com/
# The bids-specification repository is continuously scanned by the LGTM tool
# for any security and/or code vulnerabilities. You can find the alert here:
# https://lgtm.com/projects/g/bids-standard/bids-specification/
queries:
  # https://lgtm.com/rules/6770079/
  - exclude: py/unused-import
