extends: default

rules:
  line-length:
    max: 120
  indentation:
    # See https://github.com/yaml/pyyaml/issues/545 for why
    spaces: 2
    indent-sequences: true
  comments:
    level: error
    min-spaces-from-content: 1
