version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: tools/schemacode/docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: tools/schemacode/docs/requirements.txt
