version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    create_environment:
      - asdf plugin add uv https://github.com/asdf-community/asdf-uv.git
      - asdf install uv latest
      - asdf global uv latest
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv venv
    install:
      - >
        VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH
        UV_CACHE_DIR=$READTHEDOCS_VIRTUALENV_PATH/../../uv_cache
        uv sync --active --locked --group=doc

sphinx:
  configuration: tools/schemacode/docs/conf.py
