# This file encodes a lot of our intended support range, as well as some
# details about dependency availability.
#
# The majority of the information is contained in tox.envlist and testenv.deps.
[tox]
requires =
  tox>=4
  tox-uv
envlist =
  py3{10-12}-latest
  py3{13-14}{,t}-latest
  # Minimum Python with minimum deps
  py310-min
  # Python development versions
  py3{14-15}{,t}-pre
  typecheck
skip_missing_interpreters = true

# Configuration that allows us to split tests across GitHub runners effectively
[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.13t: py313t
  3.14: py314
  3.14t: py314t
  3.15: py315
  3.15t: py315t

[gh-actions:env]
DEPENDS =
  pre: pre
  full: full
  min: min

[testenv]
description = Pytest with coverage
runner =
  latest: uv-venv-lock-runner
  !latest: uv-venv-runner
labels = test
pip_pre =
  pre: true
pass_env =
  # Pass user color preferences through
  PY_COLORS
  FORCE_COLOR
  NO_COLOR
  CLICOLOR
  CLICOLOR_FORCE
set_env =
  pre: PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
  pre: UV_INDEX_STRATEGY=unsafe-best-match
  py3{13-15}t: PYTHONGIL={env:PYTHONGIL:0}
dependency_groups = tests
uv_resolution =
  min: lowest-direct

commands =
  pytest --doctest-modules \
  latest,pre: -Werror \
    --cov src --cov tests --cov-report xml:cov.xml \
    --junitxml test-results.xml \
    --durations=20 --durations-min=1.0 \
    {posargs:-n auto}

[testenv:typecheck]
description = Check type consistency
labels = check
runner = uv-venv-lock-runner
package = wheel
dependency_groups =
  tests
  types
commands =
  mypy src
  # Run separately to test against installed package's types
  mypy tests
