version: 2.1
jobs:
  build_docs_pdf:
    docker:
      - image: texlive/texlive:latest
    steps:
      # checkout code to default ~/project
      - checkout
      - run:
          name: install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | XDG_BIN_HOME=/usr/local/bin sh
      - run:
          name: install dependencies
          command: |
            apt-get update && apt install -y fonts-symbola pandoc
      - run:
          name: generate pdf version docs
          command: |
            uv sync
            source .venv/bin/activate
            cd ~/project/pdf_build_src
            bash build_pdf.sh
            mv ~/project/pdf_build_src/bids-spec.pdf ~/project/bids-spec.pdf
      - store_artifacts:
          path: bids-spec.pdf

workflows:
  search_build:
    jobs:
      - build_docs_pdf
