name: Feature request

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Suggest an idea for this project

body:

  - type: markdown
    attributes:
      value: |
        - Have you checked our [contributing guide](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md))?
          It's a helpful resource:

        - Is your idea backwards compatible?
          If not, please open an issue in the [bids-2-devel repository](https://github.com/bids-standard/bids-2-devel) instead.

        - Is there already a group working on your idea?
          Check the [BIDS extension proposals](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification)

        - Will your idea potentially require a large effort?
          Read [BEP lead guidelines](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/).


  - type: textarea
    attributes:
      label: Your idea
      description: When you suggest your idea, please try to supply (mock) examples!
