#!/usr/bin/env bash

# Execute this script from its containing directory to push to a new unique testing tag.
# This is a script which automates creation and pushing of unique tags for github actions.
# It is particularly useful when debugging the upload hooks for pypi.
# The workflow for that is to edit `.github/workflows/schemacode_ci.yml` and add a secondary branch name to the `on` section right after master.
# This will allow you to keep pushing to the branch as if it were master and unix-time tagged archives being uploaded to test.pypi.

VERSION_FILE="src/schema/SCHEMA_VERSION"

pushd ..
	export MY_BIDS_DATE="$(date +%s)"
	REAL_VERSION=$(cat "${VERSION_FILE}")
	DUMMY_VERSION="0.0.${MY_BIDS_DATE}-dev"
	echo "${DUMMY_VERSION}" > "${VERSION_FILE}"
	git commit -a -m "debug"
	git tag -a "schema-$DUMMY_VERSION" -m "debug"
	git push origin
	git push origin "schema-$DUMMY_VERSION"
	echo "${REAL_VERSION}" > "${VERSION_FILE}"
popd
unset MY_BIDS_DATE

