#!/usr/bin/env bash
#
# Description: rename all mentionings of participants to subjects
#
# Reference issues:
# - https://github.com/bids-standard/bids-2-devel/issues/14

set -eu -o pipefail

pathspec=( ':(exclude)src/CHANGES.md' ':(exclude)src/appendices/licenses.md' ':(exclude)CODE_OF_CONDUCT.md' ':(exclude)tools/bids-2.0/*' ':(exclude)tools/schemacode/bidsschematools/migrations.py' )

# Plural -- no need really for a separate invocation since plural is just singular + s
# git grep -l participants -- "${pathspec[@]}" | xargs sed -i -e 's,participants,subjects,g'

# Singular -- tricky since we want to exclude some. According to chatgpt no built in negative back lookup
# so suggested to replace with PLACEHOLDER
if git grep -q -l PLACEHOLDER -- "${pathspec[@]}"; then
    echo "Assertion error -- PLACEHOLDER already used somehow" >&2
    exit 1
fi

git grep -l '[Pp]articipant' -- "${pathspec[@]}" | \
    xargs sed -i -e 's/\(Experiment-\|as reported by the \)participant/PLACEHOLDER#\1#/g' \
    -e 's/participant/subject/g' \
    -e 's/Participant/Subject/g' \
    -e 's/PLACEHOLDER#\([^#]*\)#/\1participant/g'
