---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          skip: js,*.svg
          ignore_words_list: fo,te,als
