name: "Label PRs"
# See https://github.com/marketplace/actions/auto-labeler

on:

  pull_request_target:
    types: [opened]

jobs:

  labeler:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'bids-standard'

    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@e6fb93f2d64d8b0b78d208456f349e9e00698a5d # v2.1.4
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
