on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        id: step1
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/bids-spec.pdf
          circleci-jobs: build_docs_pdf
          job-title: Check the rendered PDF version here!
      - name: Check the URL
        run: |
          curl --fail ${{ steps.step1.outputs.url_output }} | grep $GITHUB_SHA
