name: bst

on:
  push:
    branches:
      - "master"
      - "maint/*"
    tags:
      - "schema-*"
  pull_request:
    branches:
      - "master"
      - "maint/*"
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

# Force tox and pytest to use color
env:
  FORCE_COLOR: true

permissions:
  contents: read

jobs:
  build:
    name: Build & verify package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        if: ${{ startsWith(github.ref, 'refs/tags/schema-') }}
      - name: "Build archive on tag"
        run: |
          uv run --group=tests pytest -k make_archive
        working-directory: tools/schemacode
        env:
          BIDSSCHEMATOOLS_RELEASE: 1
        if: ${{ startsWith(github.ref, 'refs/tags/schema-') }}
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          path: tools/schemacode
          attest-build-provenance-github: ${{ github.event_name != 'pull_request' }}

  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        dependencies: [latest]
        include:
          - os: macos-latest
            python-version: '3.14'
            dependencies: latest
          - os: windows-latest
            python-version: '3.14'
            dependencies: latest
          - os: ubuntu-latest
            python-version: '3.10'
            dependencies: min
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }} (uv)
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install tox
        run: uv tool install -v tox --with=tox-uv --with=tox-gh-actions

      - name: Show tox config
        run: tox c
        working-directory: tools/schemacode

      - name: Setup test suite
        run: tox run -vv --notest
        working-directory: tools/schemacode

      - name: Run test suite
        run: tox -v --skip-pkg-install --exit-and-dump-after 1200
        working-directory: tools/schemacode

      - uses: codecov/codecov-action@v5
        if: ${{ always() }}
        with:
          files: tools/schemacode/cov.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v7
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.dependencies }}-${{ matrix.architecture }}
          path: tools/schemacode/test-results.xml
        if: ${{ always() }}

  checks:
    runs-on: 'ubuntu-slim'
    continue-on-error: true
    strategy:
      matrix:
        check: ['typecheck']

    steps:
      - uses: actions/checkout@v6
      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3
          activate-environment: true
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install tox
        run: uv tool install -v tox --with=tox-uv-bare --with=tox-gh-actions
      - name: Show tox config (this call)
        run: tox c -e ${{ matrix.check }}
        working-directory: tools/schemacode
      - name: Setup check environment
        run: tox -vv --notest -e ${{ matrix.check }}
        working-directory: tools/schemacode
      - name: Run check
        run: tox -e ${{ matrix.check }}
        working-directory: tools/schemacode

  publish:
    runs-on: ubuntu-latest
    environment: "Package deployment"
    needs: [build, tox]
    permissions:
      attestations: write
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: "Test PyPI upload"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      - name: "Upload to PyPI (on tags)"
        if: startsWith(github.ref, 'refs/tags/schema-')
        uses: pypa/gh-action-pypi-publish@release/v1
