name: Lint yml files

on: [push, pull_request]

jobs:
  yml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install yamllint
    - name: Lint yml files in src/schema
      # for config, see:
      # https://yamllint.readthedocs.io/en/stable/configuration.html#custom-configuration-without-a-config-file
      run: |
        yamllint -f standard src/schema/ -c .yamllint.yml
