name: Lint yml files

on: [push, pull_request]

jobs:
  yml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install yamllint
    - name: Lint yml files in src/schema
      run: yamllint -f standard src/schema/
